### ISSUE TITLE
[DESIGN]: Responsive x Padding

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#138]
As a user, I would like to see less horizontal padding on smaller screens so that the content has more space.

**Describe the solution you'd like**

I will suggest maybe when the screen is smaller to remove the `px` padding so the content can spread about 95% of the screen width.
![Screenshot 2024-06-08 at 9 10 44 PM](https://github.com/Learn-Build-Teach/deals-for-devs/assets/19928453/79ed4539-aa44-4df8-a34b-dce0c0eb7084)

**Comment by 24HourDeveloper** [comment]
I started working on the issue today but it seems as if the issue was resolved with `<section className='w-full'>` I'll add a video below showing the response with this class.

https://github.com/Learn-Build-Teach/deals-for-devs/assets/19928453/0052e3ae-063f-44dc-ba96-e9959a8e9a3c


I will suggest maybe when the screen is smaller to remove the `px` padding so the content can spread about 95% of the screen width.
![Screenshot 2024-06-08 at 9 10 44 PM](https://github.com/Learn-Build-Teach/deals-for-devs/assets/19928453/79ed4539-aa44-4df8-a34b-dce0c0eb7084)
