### ISSUE TITLE
[BUG]: Malformatted Subscribe Confirm Email

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#165]
**Describe the bug**
The confirmation email isn't formatted correctly. Specifically, the `Confirm Email` button doesn't get moved to its own line.

![image](https://github.com/Learn-Build-Teach/deals-for-devs/assets/5391915/5435a2c5-ef7f-44dd-8c90-8aead40ce92e)

**To Reproduce**

**Comment by 24HourDeveloper** [comment]
@jamesqquick I believe I figured it out. I wasn't able to recreate the issue by resizing the screen I had to set the table width around the button to a smaller width and the button split. Due to the button being an anchor tag its default display is inline. When I set the anchor to  block and set width to max-content the button was intact despite the table width size being 20px.

![Screenshot 2024-06-15 at 3 32 51 PM](https://github.com/Learn-Build-Teach/deals-for-devs/assets/19928453/3f7e9905-3e2e-45ba-a09c-5e7dd91c0bb5)
