### ISSUE TITLE
Contant Layout Shift (CLS) on Deals Cards

### ISSUE THREAD

**Issue by ryandotfurrer** [Learn-Build-Teach/deals-for-devs#92]
Due to the Deals Cards border property growing on hover, it is causing layout shift.
# Visual Example
![Demo of content layer shift on when hovering over deals cards with long descriptions](https://github.com/Learn-Build-Teach/deals-for-devs/assets/40150036/cb71abdf-4926-4a2b-8f01-6f6d125a49df)
# Current Code

```js
<Link
      href={deal.link}
      className="... hover:border-4 ..."
      target="_blank"
      rel="noopener noreferrer"
    >
```

As long as it does not mess with acessibilty, perhaps we can change `border` to `outline` when `focused` or `hovered`? This would eliminate the CLS we're currently seeing.

**Comment by ryandotfurrer** [comment]
@jamesqquick what are your thoughts on using outline here rather than margin? If ok, I'm happy to take care of this one.

**Comment by jamesqquick** [comment]
@ryandotfurrer that sounds great. Please do!

**Comment by jamesqquick** [comment]
@ryandotfurrer Actually wait. Let's not spend time on that since we need to redo the card design anyway. Here's what the cards should look like in the new design.

![CleanShot 2024-03-27 at 08 32 32](https://github.com/Learn-Build-Teach/deals-for-devs/assets/5391915/80645224-0e07-4f4e-a273-891ccd8124b6)

Want to take on an issue to tackle that?
